/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barberiabd.vista;

import barberiabd.controlador.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Andrea Calderon
 */
public class CrearMiembro extends javax.swing.JFrame {

    static String nombre;
    static String direccion;
    static int id;
    static int telefono;
    static String contraseña;
    static String tipo_String;
    static int maquinaAsignada;
    static int porcentajeComision;

    public CrearMiembro() {
        initComponents();
        setResizable(false);
        setSize(425, 460);
        setTitle("Registrar nuevo miembro");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#dbdccd"));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        crear_btn = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();
        nombre_tf = new javax.swing.JTextField();
        direccion_tf = new javax.swing.JTextField();
        id_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JTextField();
        tel_tf = new javax.swing.JTextField();
        maquinaAsig_tf = new javax.swing.JTextField();
        porcentajeCom_tf = new javax.swing.JTextField();
        tipoNivel_cmb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vector.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 70));

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese su nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese su dirección:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese su identificación:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel5.setText("Tipo ocupación:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese su telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese máquina asignada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel8.setText("Ingrese porcentaje comisión:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel9.setText("Ingrese una contraseña:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        crear_btn.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        crear_btn.setText("Crear");
        crear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_btnActionPerformed(evt);
            }
        });
        getContentPane().add(crear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        salir_btn.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        salir_btn.setText("Regresar");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });
        getContentPane().add(salir_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        nombre_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(nombre_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 110, 20));

        direccion_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(direccion_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 110, 20));

        id_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 20));

        pass_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(pass_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, 20));

        tel_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(tel_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 110, 20));

        maquinaAsig_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(maquinaAsig_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 110, 20));

        porcentajeCom_tf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(porcentajeCom_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 110, 20));

        tipoNivel_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Barbero" }));
        getContentPane().add(tipoNivel_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel10.setText("Si se está ingresando un barbero recuerde llenar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 340, 20));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setText("los siguientes campos:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        dispose();
        Administrador retorno = new Administrador();
        retorno.setVisible(true);
    }//GEN-LAST:event_salir_btnActionPerformed

    private void crear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_btnActionPerformed
        int validacion = 0, validacionB = 0, tipo_cbm;
        nombre = nombre_tf.getText().trim();
        direccion = direccion_tf.getText().trim();
        id = Integer.parseInt(id_tf.getText().trim());
        String telefono_string = tel_tf.getText().trim();
        contraseña = pass_tf.getText().trim();
        tipo_cbm = tipoNivel_cmb.getSelectedIndex();

        if (nombre.equals("")) {
            nombre_tf.setBackground(Color.red);
            validacion++;
        }
        if (direccion.equals("")) {
            direccion = null;
        }
        if ((Integer.toString(id)).equals("")) {
            id_tf.setBackground(Color.red);
            validacion++;
        }
        if (contraseña.equals("")) {
            pass_tf.setBackground(Color.red);
            validacion++;
        }
        if (tipo_cbm == 1) {
            tipo_String = "Administrador";
        } else {
            tipo_String = "Barbero";
        }
        if (tipo_String.equals("Administrador") && validacion == 0) {
            if (telefono_string.equals("")) {
                int telefono = 0;
            }
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select id from administrador where id = '" + id + "'");
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    id_tf.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Identificacion ya existente");
                    cn.close();
                } else {
                    cn.close();
                    if (validacion == 0) {
                        try {
                            Connection cn2 = Conexion.conectar();
                            PreparedStatement pst2 = cn2.prepareStatement(
                                    "insert into administrador values (?,?,?,?,?)"); //Se agregan los datos a la base de datos

                            pst2.setInt(1, id);
                            pst2.setString(2, nombre);
                            pst2.setString(3, direccion);
                            pst2.setInt(4, telefono);
                            pst2.setString(5, contraseña);

                            pst2.executeUpdate();
                            cn2.close();

                            Limpiar();

                            nombre_tf.setBackground(Color.green);
                            id_tf.setBackground(Color.green);
                            direccion_tf.setBackground(Color.green);
                            tel_tf.setBackground(Color.green);
                            pass_tf.setBackground(Color.green);

                            JOptionPane.showMessageDialog(null, "Registro exitoso");

                        } catch (SQLException e) {
                            System.err.println("Error en registrar administrador" + e);
                            JOptionPane.showMessageDialog(null, "Error al registrar, contacte al desarrollador.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos obligatorios.");
                    }
                }
            } catch (SQLException e) {
                System.err.println("Error en validar id del usuario." + e);
                JOptionPane.showMessageDialog(null, "Error al comparar usuario");
            }
        }

        if (validacion == 0 && tipo_String.equals("Barbero")) {
            if (telefono_string.equals("")) {
                tel_tf.setBackground(Color.red);
                validacionB++;
            }
            if ((maquinaAsig_tf.getText().trim()).equals("")) {
                maquinaAsig_tf.setBackground(Color.red);
                validacionB++;
            }
            if ((porcentajeCom_tf.getText().trim()).equals("")) {
                porcentajeCom_tf.setBackground(Color.red);
                validacionB++;
            }
            if (validacionB == 0) {
                maquinaAsignada = Integer.parseInt(maquinaAsig_tf.getText().trim());
                porcentajeComision = Integer.parseInt(porcentajeCom_tf.getText().trim());
                telefono = Integer.parseInt(telefono_string);
                try {
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "select id from barbero where id = '" + id + "'");
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Identificacion ya existente");
                        cn.close();
                    } else {
                        if (validacion == 0) {
                            try {
                                Connection cn2 = Conexion.conectar();
                                PreparedStatement pst2 = cn2.prepareStatement(
                                        "insert into barbero values (?,?,?,?,?,?,?)"); //Se agregan los datos a la base de datos

                                pst2.setInt(1, id);
                                pst2.setString(2, nombre);
                                pst2.setString(3, direccion);
                                pst2.setInt(4, telefono);
                                pst2.setInt(5, maquinaAsignada);
                                pst2.setInt(6, porcentajeComision);
                                pst2.setString(7, contraseña);

                                pst2.executeUpdate();
                                cn2.close();

                                JOptionPane.showMessageDialog(null, "Registro exitoso");

                            } catch (SQLException e) {
                                System.err.println("Error en registrar Barbero" + e);
                                JOptionPane.showMessageDialog(null, "Error al registrar, contacte al desarrollador.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
                        }
                    }
                } catch (SQLException e) {
                    System.err.println("Error en validar id del usuario." + e);
                    JOptionPane.showMessageDialog(null, "Error al comparar usuario");
                }
            }
        }
    }//GEN-LAST:event_crear_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear_btn;
    private javax.swing.JTextField direccion_tf;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maquinaAsig_tf;
    private javax.swing.JTextField nombre_tf;
    private javax.swing.JTextField pass_tf;
    private javax.swing.JTextField porcentajeCom_tf;
    private javax.swing.JButton salir_btn;
    private javax.swing.JTextField tel_tf;
    private javax.swing.JComboBox<String> tipoNivel_cmb;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        nombre_tf.setText("");
        id_tf.setText("");
        direccion_tf.setText("");
        tel_tf.setText("");
        pass_tf.setText("");
        tipoNivel_cmb.setSelectedIndex(0);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LogoP.png"));
        return retValue;
    }
}
