/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barberiabd.vista;

import barberiabd.controlador.Conexion;
import static barberiabd.vista.GestionarVenta.codventa;
import static barberiabd.vista.InformeAdministrador.id_admin;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea Calderon
 */
public class InformeVentas extends javax.swing.JFrame {

    public static String user_update = "";
    DefaultTableModel model = new DefaultTableModel();
    static int ventaIngresado;

    public InformeVentas() {
        initComponents();
        setResizable(false);
        setSize(620, 370);
        setTitle("Informe de ventas");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#dbdccd"));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select fecha, idCliente, idBarbero, costo, propina from venta");

            ResultSet rs = pst.executeQuery();
            Tabla_Ventas = new JTable(model);
            jScrollPane1.setViewportView(Tabla_Ventas);
            model.addColumn("Fecha");
            model.addColumn("Codigo cliente");
            model.addColumn("Codigo barbero");
            model.addColumn("Costo");
            model.addColumn("Propina");

            while (rs.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getString(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
            Tabla_Ventas.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int fila_point = Tabla_Ventas.rowAtPoint(e.getPoint());
                    int columna_point = 1;
                    if (fila_point > -1) {
                       JOptionPane.showMessageDialog(null, "No se puede modificar la venta."); 
                    }
                }
            });
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar información contacte al administrador. ");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LogoP.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Ventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regresar_btn = new javax.swing.JButton();
        venta_jtf = new javax.swing.JTextField();
        buscarVenta_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla_Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Ventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 130));

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel1.setText("Lista de los administradores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vector.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 80, 70));

        regresar_btn.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        regresar_btn.setText("Regresar");
        regresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(regresar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        venta_jtf.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        venta_jtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venta_jtfActionPerformed(evt);
            }
        });
        getContentPane().add(venta_jtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 110, 20));

        buscarVenta_btn.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        buscarVenta_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        buscarVenta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVenta_btnActionPerformed(evt);
            }
        });
        getContentPane().add(buscarVenta_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 40, 40));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setText("Para buscar una venta ingrese su codigo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_btnActionPerformed
        dispose();
        Administrador retorno = new Administrador();
        retorno.setVisible(true);
    }//GEN-LAST:event_regresar_btnActionPerformed

    private void venta_jtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venta_jtfActionPerformed

    }//GEN-LAST:event_venta_jtfActionPerformed

    private void buscarVenta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVenta_btnActionPerformed
      String ventaIngresado_string = venta_jtf.getText().trim();  
        if (!ventaIngresado_string.equals("")) {
            ventaIngresado = Integer.parseInt(ventaIngresado_string);
            if (encuentraId("venta", "id", ventaIngresado) == true) {
                dispose();
                GestionarVenta infoventa = new GestionarVenta();
                infoventa.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No existe la venta que está buscando");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe de ingresar el id de la venta.");
        }
    }//GEN-LAST:event_buscarVenta_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Ventas;
    private javax.swing.JButton buscarVenta_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar_btn;
    private javax.swing.JTextField venta_jtf;
    // End of variables declaration//GEN-END:variables
private static boolean encuentraId(String tabla, String nombreId, int id) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select " + nombreId + " from " + tabla + " where " + nombreId + " = '" + id
                    + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return true;

            } else {
                return false;
            }
        } catch (SQLException e) {
            return false;
        }
    }
}
