/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barberiabd.vista;

import barberiabd.controlador.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Andrea Calderon
 */
public class ReporteVenta extends javax.swing.JFrame {
    static int codventa,codcliente,codbarbero,costo,propina;
    static String fecha;

    public ReporteVenta() {
        initComponents();
        setResizable(false);
        setSize(400, 310);
        setTitle("Informe de ventas");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#dbdccd"));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select tiemposql, idVenta, idCliente, idBarbero, costo, propina from venta");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                fecha = rs.getString("tiemposql");
                codventa = rs.getInt("idVenta");
                codcliente = rs.getInt("idCliente");
                codbarbero = rs.getInt("idBarbero");
                costo = rs.getInt("costo");
                propina = rs.getInt("propina");
            }
            
            fecha_jl.setText(fecha);
            idbarbero_jl.setText(Integer.toString(codbarbero));
            idcliente_jl.setText(Integer.toString(codcliente));
            codigoVenta_jl.setText(Integer.toString(codventa));
            costo_jl.setText(Integer.toString(costo));
            propina_jl.setText(Integer.toString(propina));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar venta. Contacte al desarrollador");
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LogoP.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codigoVenta_jl = new javax.swing.JLabel();
        idcliente_jl = new javax.swing.JLabel();
        idbarbero_jl = new javax.swing.JLabel();
        costo_jl = new javax.swing.JLabel();
        propina_jl = new javax.swing.JLabel();
        regresar_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fecha_jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vector.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 70));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel2.setText("Codigo venta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setText("Id cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel4.setText("Id barbero:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel5.setText("Costo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel6.setText("Propina:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        codigoVenta_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(codigoVenta_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, 20));

        idcliente_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(idcliente_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, 20));

        idbarbero_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(idbarbero_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 100, 20));

        costo_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(costo_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, 20));

        propina_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(propina_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 100, 20));

        regresar_btn.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        regresar_btn.setText("Regresar");
        regresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(regresar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel7.setText("Fecha");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 20));

        fecha_jl.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        getContentPane().add(fecha_jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 110, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_btnActionPerformed
        this.dispose();
        InformeVentas venta = new InformeVentas();
        venta.setVisible(true);
    }//GEN-LAST:event_regresar_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoVenta_jl;
    private javax.swing.JLabel costo_jl;
    private javax.swing.JLabel fecha_jl;
    private javax.swing.JLabel idbarbero_jl;
    private javax.swing.JLabel idcliente_jl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel propina_jl;
    private javax.swing.JButton regresar_btn;
    // End of variables declaration//GEN-END:variables
}
